#!/bin/bash
# Inspired by elegaanz's update-theme script for mako

source "${HOME}/.cache/wal/colors.sh"

conffile="$XDG_CONFIG_HOME/mako/config"

# Associative array
declare -A colors
colors=(
    ["background-color"]="$background"
    ["text-color"]="$foreground"
    ["border-color"]="$color1"
)

for color_name in "${!colors[@]}"; do
    # replace first occurance of each color
    sed -i "0,/^$color_name.*/{s//$color_name=${colors[$color_name]}/}" $conffile
done

#for color_name in "${!colors[@]}"; do
##   # repliace first occurance of each color in config file
#    sed -i "0,/^$color_name.*/{s//$color_name=${colors[$color_name]}/}" $conffile
#done

makoctl reload
