version = "2"

[com]
port = 50101
address = "::"

[player]
music_dirs = ["/mnt/storage/Entertainment/Music"]
library_scan_depth = 10
loop_mode = "playlist"
volume = 100
speed = 10
gapless = true
use_mediacontrols = true
set_discord_status = true
random_track_quantity = 20
random_album_min_quantity = 5

[player.remember_position]
music = "no"
podcast = "yes"

[player.seek_step]
short_tracks = 5
long_tracks = 30

[podcast]
concurrent_downloads_max = 3
max_download_retries = 3
download_dir = "/home/Timmy/Music/podcast"
