[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "[C]ompress with ouch"

[[manager.prepend_keymap]]
on = ["E"]
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

# marks for jumping
[[manager.prepend_keymap]]
on = ["<S-m>"]
run = "plugin bookmarks --args=save"
desc = "[m]ark to key"

[[manager.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks --args=jump"
desc = "jump to mark"

[[manager.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks --args=delete"
desc = "[b]ookmark [d]elete"

[[manager.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks --args=delete_all"
desc = "[b]ookmark [D]elete ALL"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "[c]h[m]od files"

# undo on deleted items
[[manager.prepend_keymap]]
on = ["d", "u"]
run = "plugin restore"
desc = "[d]elete [u]ndo"

[[manager.prepend_keymap]]
on = ["d", "d"]
run = "remove"
desc = "[d]o [d]elete"

[[manager.prepend_keymap]]
on = ["d", "D"]
run = "remove --permanently"
desc = "[d]o [D]elete permanently"

# ripdrag
[[manager.prepend_keymap]]
on = "<C-n>"
run = '''shell 'ripdrag -i -s 124 -W 128 -H 128 -a "$@" -x 2>/dev/null &' --confirm'''

# yank file contents to clipboard 
[[manager.prepend_keymap]]
on = ['c', 'C']
run = ["plugin copy-file-contents"]
# run = ['''
# 	shell 'for path in "$@"; do cat "$path"; done | wl-copy -t text/uri-list'
# ''', "yank"]
desc = "[c]opy [C]ontents"

# yank file
[[manager.prepend_keymap]]
on = ['c', 'u']
run = [
	'''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''',
	"yank",
]
desc = "[c]opy [u]ri"

[[manager.prepend_keymap]]
on = "<C-y>"
run = ["plugin wl-clipboard"]

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd --args=block"
desc = "[o]pen with command in the terminal"

[[manager.prepend_keymap]]
on = "O"
run = "plugin open-with-cmd"
desc = "[O]pen with command"

# search for ignored files as well (e.g. files listed by .*ignore)
[[manager.prepend_keymap]]
on = "<C-s>"
run = 'search --via=fd --args="--no-ignore"'
desc = "[s]earch file name (inc. ignored)"

[[manager.prepend_keymap]]
on = "<C-S>"
run = 'search --via=rg --args="--no-ignore"'
desc = "[S]earch file content (inc. ignored)"
