[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch zip"
desc = "[C]ompress with ouch"

[[mgr.prepend_keymap]]
on = ["E"]
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

# marks for jumping
[[mgr.prepend_keymap]]
on = ["<S-m>"]
run = "plugin bookmarks save"
desc = "[m]ark to key"

[[mgr.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks jump"
desc = "jump to mark"

[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks delete"
desc = "[b]ookmark [d]elete"

[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks delete_all"
desc = "[b]ookmark [D]elete ALL"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "[c]h[m]od files"

# undo on deleted items
[[mgr.prepend_keymap]]
on = ["d", "u"]
run = "plugin restore"
desc = "[d]elete [u]ndo"

[[mgr.prepend_keymap]]
on = ["<Delete>"]
run = "remove"
desc = "[d]o [d]elete"

[[mgr.prepend_keymap]]
on = ["d", "d"]
run = "remove"
desc = "[d]o [d]elete"

[[mgr.prepend_keymap]]
on = ["D"]
run = "noop"
# prefer lower keybind for safety

[[mgr.prepend_keymap]]
on = ["d", "<A-C-P>"]
run = "remove --permanently"
desc = "do delete permanently"

# ripdrag
[[mgr.prepend_keymap]]
on = "<C-n>"
run = '''shell 'ripdrag -i -s 124 -W 128 -H 128 -a "$@" -x 2>/dev/null &' --confirm'''

# yank file contents to clipboard 
[[mgr.prepend_keymap]]
on = ['c', 'C']
run = ["plugin copy-file-contents"]
# run = ['''
# 	shell 'for path in "$@"; do cat "$path"; done | wl-copy -t text/uri-list'
# ''', "yank"]
desc = "[c]opy [C]ontents"

# yank file
[[mgr.prepend_keymap]]
on = ['c', 'u']
run = [
	'''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
	''',
	"yank",
]
desc = "[c]opy [u]ri"

[[mgr.prepend_keymap]]
# on = "<C-y>"
# run = ["plugin wl-clipboard"]
desc = "[c]opy to wl-clipboard"

on = "<C-y>"
run = ["plugin system-clipboard"]

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd block"
desc = "[o]pen with command in the terminal"

[[mgr.prepend_keymap]]
on = "O"
run = "plugin open-with-cmd"
desc = "[O]pen with command"

# search for ignored files as well (e.g. files listed by .*ignore)
[[mgr.prepend_keymap]]
on = "<C-s>"
run = 'search --via=fd --args="--no-ignore"'
desc = "[s]earch file name (inc. ignored)"

[[mgr.prepend_keymap]]
on = "<C-S>"
run = 'search --via=rg --args="--no-ignore"'
desc = "[S]earch file content (inc. ignored)"

# fd exclude
[[mgr.prepend_keymap]]
on = "<C-f>"
run = 'search --via=fd --args="-E"'
desc = "[f]ind exclude"
#
# # do not include .snapshots folder in searches
# [[manager.prepend_keymap]]
# on = "<f>"
# run = 'search --via=fd --args="-E .snapshots"'
# desc = "[f]ind filenames"

# fd only directories
[[mgr.prepend_keymap]]
on = "<A-f>"
run = 'search --via=fd --args="-t d"'
desc = "[f]ind directories"

# relative motions
[[mgr.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"
#
[[mgr.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["E"]
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

# smart enter, never open directories (which will open in nvim)
[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# # hide/show preview
# [[mgr.prepend_keymap]]
# on   = "T"
# run  = "plugin toggle-pane min-preview"
# desc = "Show or hide the preview pane"

# max/restore preview
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# Force to use keys on pickers
[[confirm.prepend_keymap]]
on = "<Enter>"
run = "close"
