[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "[C]ompress with ouch"

[[manager.prepend_keymap]]
on = ["E"]
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

# [[manager.prepend_keymap]]
# on = ["C"]
# run = "plugin ouch --args=zip"
# desc = "Compress with ouch"
#
# [[manager.prepend_keymap]]
# on = ["C"]
# run = "plugin ouch --args=zip"
# desc = "Compress with ouch"
#
# [[manager.prepend_keymap]]
# on = ["C"]
# run = "plugin ouch --args=zip"
# desc = "Compress with ouch"
#
# [[manager.prepend_keymap]]
# on = ["C"]
# run = "plugin ouch --args=zip"
# desc = "Compress with ouch"

# relative-motions mimic vim
# [[manager.prepend_keymap]]
# on = ["1"]
# run = "plugin relative-motions --args=1"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["2"]
# run = "plugin relative-motions --args=2"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["3"]
# run = "plugin relative-motions --args=3"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["4"]
# run = "plugin relative-motions --args=4"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["5"]
# run = "plugin relative-motions --args=5"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["6"]
# run = "plugin relative-motions --args=6"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["7"]
# run = "plugin relative-motions --args=7"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["8"]
# run = "plugin relative-motions --args=8"
# desc = "Move in relative steps"
#
# [[manager.prepend_keymap]]
# on = ["9"]
# run = "plugin relative-motions --args=9"
# desc = "Move in relative steps"
#
# # move tab buttons to alt+#
# [[manager.prepend_keymap]]
# on = ["<A-1>"]
# run = "tab_switch 0"
# desc = "Switch to the first tab"
#
#
# [[manager.prepend_keymap]]
# on = ["<A-2>"]
# run = "tab_switch 1"
# desc = "Switch to the second tab"
#
#
# [[manager.prepend_keymap]]
# on = ["<A-3>"]
# run = "tab_switch 2"
# desc = "Switch to the third tab"
#
#
# [[manager.prepend_keymap]]
# on = ["<A-4>"]
# run = "tab_switch 3"
# desc = "Switch to the fourth tab"
#
# [[manager.prepend_keymap]]
# on = ["<A-5>"]
# run = "tab_switch 4"
# desc = "Switch to the fifth tab"
#
#
# [[manager.prepend_keymap]]
# on = ["<A-6>"]
# run = "tab_switch 5"
# desc = "Switch to the sixth tab"
#
#
# [[manager.prepend_keymap]]
# on = ["<A-7>"]
# run = "tab_switch 6"
# desc = "Switch to the seventh tab"
#
#
# [[manager.prepend_keymap]]
# on = ["<A-8>"]
# run = "tabs_witch 7"
# desc = "Switch to the eighth tab"
#
# [[manager.prepend_keymap]]
# on = ["<A-9>"]
# run = "tab_switch 8"
# desc = "Switch to the ninth tab"

# vim f function, but no F, rather have filter?
# [[manager.prepend_keymap]]
# on = "f"
# run = "plugin jump-to-char"
# desc = "Jump to char"

# marks for jumping
[[manager.prepend_keymap]]
on = ["<S-m>"]
run = "plugin bookmarks --args=save"
desc = "[m]ark to key"

[[manager.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks --args=jump"
desc = "jump to mark"

[[manager.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks --args=delete"
desc = "[b]ookmark [d]elete"

[[manager.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks --args=delete_all"
desc = "[b]ookmark [D]elete ALL"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "[c]h[m]od files"

# undo on deleted items
[[manager.prepend_keymap]]
on = ["d", "u"]
run = "plugin restore"
desc = "[d]elete [u]ndo"

[[manager.prepend_keymap]]
on = ["d", "d"]
run = "remove"
desc = "[d]o [d]elete"

[[manager.prepend_keymap]]
on = ["d", "D"]
run = "remove --permanently"
desc = "[d]o [D]elete permanently"

# ripdrag
[[manager.prepend_keymap]]
on = "<C-n>"
run = '''shell 'ripdrag -i -s 124 -W 128 -H 128 -a "$@" -x 2>/dev/null &' --confirm'''

# yank file contents to clipboard 
[[manager.prepend_keymap]]
on = ['c', 'C']
run = ["plugin copy-file-contents"]
# run = ['''
# 	shell 'for path in "$@"; do cat "$path"; done | wl-copy -t text/uri-list'
# ''', "yank"]
desc = "[c]opy [C]ontents"

# yank file
[[manager.prepend_keymap]]
on = ['c', 'u']
run = [
	'''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''',
	"yank",
]
desc = "[c]opy [u]ri"
