[manager]
sort_by = "mtime"
sort_reverse = true

[preview]
image_delay = 0

# [[plugin.append_previewers]]
# name = "*"
# run = "hexyl"

[[plugin.prepend_previewers]]
name = "*.md"
run = "glow"

[[plugin.prepend_previewers]]
mime = "application/*zip"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-tar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-bzip2"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-7z-compressed"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-rar"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-xz"
run = "ouch"

[[plugin.prepend_previewers]]
name = "*/"
run = "eza-preview"

# [[plugin.prepend_fetchers]]
# id = "mime"
# if = "!(mime|dummy)"
# name = "*"
# run = "mime-ext"
# prio = "high"

# # Use allmytoes for xdg-compliant thumbnails
# # Prepend previewers
# [[plugin.prepend_previewers]]
# mime = "image/svg+xml"
# run = "magick"
#
# [[plugin.prepend_previewers]]
# mime = "image/heic"
# run = "magick"
#
# [[plugin.prepend_previewers]]
# mime = "image/jxl"
# run = "magick"
#
# [[plugin.prepend_previewers]]
# mime = "image/*"
# run = "allmytoes"
#
# # Prepend preloaders
# [[plugin.prepend_preloaders]]
# mime = "image/svg+xml"
# run = "magick"
#
# [[plugin.prepend_preloaders]]
# mime = "image/heic"
# run = "magick"
#
# [[plugin.prepend_preloaders]]
# mime = "image/jxl"
# run = "magick"
#
# [[plugin.prepend_preloaders]]
# mime = "image/*"
# run = "allmytoes"

# git.yazi
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[opener]
extract = [
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
