#!/bin/bash

vim_server_dir="/run/user/1000"
theme_name=pywal-lush

#echo Applying color theme to ongoing vim instances...

# If glob doesn't match, it will loop once with the unexpanded pattern
# See https://mywiki.wooledge.org/BashFAQ/020
#for file in "$vim_server_dir"/nvim.*.0; do
#	printf "Applying colorscheme to instance %s\n" "$(sed -e 's>.*\/>>' <<< "$file")"
#	nvr --nostart --servername "$file" -c "colorscheme $theme_name"
#done

# An alternative method
find "$vim_server_dir" -maxdepth 1 -name "nvim.*.0" \
-exec echo Applying colorscheme to instance "$(sed -e 's>.*\/>>' <<< "{}")" \; \
-exec nvr -s --nostart --servername "{}" -c "LushwalCompile" \; &
# -exec nvr --nostart --servername "{}" -c "colorscheme $theme_name" \;

#echo Done!
