#!/bin/env sh

# File scroller helper utility
#
# Trivially retrieve files from a directory by "scrolling".


get_files() {
    find "$scroll_path" -maxdepth 1 ! -name ".*" -type f
}

# Return the index of this file in the folder
# 
# If the scroll init doesn't exist, return index 0
# args
#   $1: image to search for (optional, looks for $scroll_init by default)
# shellcheck disable=SC2120
get_index() {
    if [ -e "$scroll_init" ]; then
        get_files | grep -n "${1:-$scroll_init}" | cut -d: -f1
    else
        echo 0
    fi
}

# Get the file at this index
# args
#   $1: index (default: current image)
# shellcheck disable=SC2120
get_file() {
    if [ -z $1 ]; then
        echo "$scroll_init"
        return
    fi

    get_files | sed -n "${1}p"
}

get_max() {
    get_files | wc -l
}

# Get the next file after $1
# args:
#   $1: file in path (default first file)
get_next() {
    if [ -z "$1" ]; then
        get_file 1
        return
    fi

    n=$(( $(get_index) + 1 ))

    if [ $n -gt $(get_max) ]; then
        n=1
    fi

    get_file $n
}

get_prev() {
    if [ -z "$1" ]; then
        get_file $(get_max)
        return
    fi

    p=$(( $(get_index) - 1 ))

    if [ $p -lt 1 ]; then
        p=$(get_max)
    fi

    get_file $p
}

truncate_file() {
    sed 's/\/[^\/]*$//' <<< $1
}

# Main
while getopts "p:i:" opt; do
    case $opt in
        p)
            scroll_path=$(realpath "$OPTARG")
            ;;
        i)
            scroll_init=$(realpath "$OPTARG")
            ;;
        \?)
            ;;
    esac
done

if [ -z "$scroll_path" ]; then
    echo "Error: A path to scroll files must be provided"
    exit 1
elif [ -n "$scroll_init" ]; then
    if [ -d "$scroll_init" ]; then
        echo "Error: $scroll_init is a directory"
        exit 1
    elif [ "$scroll_path" != "$(truncate_file "$scroll_init")" ]; then
        echo "Error: $scroll_init does not exist in scroll path $scroll_path"
        exit 1
    fi
fi

shift $((OPTIND - 1))

case $1 in
    next|n)
        get_next "$scroll_init"
        ;;
    prev|p)
        get_prev "$scroll_init"
        ;;
    *)
        echo "Unknown subcommand $1"
        ;;
esac
