#!/bin/env bash

# Orchestrator of fscroll and sync-theme

source ~/.env_functions

WAL_PICTURES="$XDG_PICTURES_DIR"/wal
WAL_LIB=~/.local/lib/mywal

# Temporarily path for trivial access to helper scripts
pathprepend "$WAL_LIB" PATH

# Get current wallpaper as defined by wal
#
# wal does not add a newline to the output of the file, we fix it
get_current_wallpaper() {
	# sed -e '$a\' <"$XDG_CACHE_HOME/wal/wal"
	cat "$XDG_CACHE_HOME/wal/wal"
}

# case "$1" in
#     next|n)
#         img=$(fscroll -p "$WAL_PICTURES" -i "$(get_current_wallpaper)" n)
#         ;;
#     prev|p)
#         img=$(fscroll -p "$WAL_PICTURES" -i "$(get_current_wallpaper)" p)
#         ;;
#	  reload|r)
#         img=$(fscroll -p "$WAL_PICTURES" -i "$(get_current_wallpaper)" r)
#     *)
#         echo "Unknown subcommand $1"
#         exit 1
#         ;;
# esac

img=$(fscroll -p "$WAL_PICTURES" -i "$(get_current_wallpaper)" "$1")
swww img "$img" --transition-type any --transition-duration 1 --transition-fps 60 &
# sleep 1

sync "$img"
